Kubernetes CIS v1.7.0
turbot/steampipe-mod-kubernetes-compliance pull request #35
Opened 2023-05-12 11:53 UTC by karanpopat

### Checklist
- [ ] Issue(s) linked

2023-05-15 10:53 UTC, rajlearner17 commented on cis_v170/section_5.sp
> +  cis_v170_5_2_common_tags = merge(local.cis_v170_5_common_tags, {
@karanpopat, should this section be removed, as we are not making it part of this CIS version?

2023-05-15 10:54 UTC, rajlearner17 commented on cis_v170/cis.sp
> +  children = [
Add 
```
description   = "CIS v1.7.0 benchmark provides prescriptive guidance for establishing a secure configuration posture for Kubernetes 1.25."
```

2023-05-15 11:21 UTC, rajlearner17 approved these changes
LGTM after minor changes and local execution with minikube

2023-05-17 07:25 UTC, rajlearner17 approved these changes
LGTM

2023-05-17 12:47 UTC, misraved reviewed
@karanpopat please take a look at the minor review comments.

Also, please update the doc files to mention about the new CIS benchmark.

2023-05-17 12:47 UTC, misraved commented on query/role.sp
> +      -- Required Columns
```suggestion

```

2023-05-17 12:47 UTC, misraved commented on query/role.sp
> +      -- Additional Dimensions
```suggestion

```

2023-05-17 13:47 UTC, madhushreeray30 requested changes
Please look at the comments. Thanks!!

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_1_3.md
> +
```suggestion

The principle of least privilege recommends that users are provided only the access required for their role and nothing more. The use of wildcard rights grants is likely to provide excessive rights to the Kubernetes API.

```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_1_6.md
> +attacks where an attacker is able to compromise a single pod in the cluster.
```suggestion
Service accounts tokens should not be mounted in pods except where the workload running in the pod explicitly needs to communicate with the API server.

Mounting service account tokens inside pods can provide an avenue for privilege escalation attacks where an attacker is able to compromise a single pod in the cluster.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_1_6.md
> +**References**
We do not keep references in the docs.

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_1_6.md
> +
Add default value.

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_3_2.md
> +communicate with each other and other network endpoints.
```suggestion
Running different applications on the same Kubernetes cluster creates a risk of one compromised application attacking a neighboring application. Network segmentation is important to ensure that containers can communicate only with those they are supposed to. A network policy is a specification of how selections of pods are allowed to communicate with each other and other network endpoints.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_3_2.md
> +namespace.
```suggestion
Network Policies are namespace scoped. When a network policy is introduced to a given namespace, all traffic not allowed by the policy is denied. However, if there are no network policies in a namespace all traffic will be allowed into and out of the pods in that namespace.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_3_2.md
> +Follow the documentation and create **NetworkPolicy** objects as you need them. By default, network policies are not created.
```suggestion
Follow the documentation and create `NetworkPolicy` objects as you need them. By default, network policies are not created.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_3_2.md
> +**References**
Please add Default Value and remove references.

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_2.md
> +Enable docker/default seccomp profile in your pod definitions.
```suggestion
Enable `docker/default` seccomp profile in your pod definitions.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_2.md
> +within the container.
```suggestion
Seccomp (secure computing mode) is used to restrict the set of system calls applications can make, allowing cluster administrators greater control over the security of workloads running in the cluster. Kubernetes disables seccomp profiles by default for historical reasons. You should enable it to ensure that the workloads have restricted actions available within the container.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_2.md
> +Use security context to enable the docker/default seccomp profile in your pod definitions.
```suggestion
Use security context to enable the `docker/default` seccomp profile in your pod definitions. An example is as below:

```bash
securityContext:
  seccompProfile:
    type: RuntimeDefault
```bash 
    
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_2.md
> +2. https://docs.docker.com/engine/security/seccomp/
Add default value and remove references.

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_4.md
> +controls more difficult.
```suggestion
Kubernetes provides a default namespace, where objects are placed if no namespace is specified for them. Placing objects in this namespace makes application of RBAC and other controls more difficult.

Resources in a Kubernetes cluster should be segregated by namespace, to allow for security controls to be applied at that level and to make it easier to manage resources.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_4.md
> +resources and that all new resources are created in a specific namespace.
```suggestion
Ensure that namespaces are created to allow for appropriate segregation of Kubernetes resources and that all new resources are created in a specific namespace.
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/docs/cis_v170_5_7_4.md
> +resources and that all new resources are created in a specific namespace.
Also add default value.

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/section_5.sp
> +  description   = "Seccomp (secure computing mode) is used to restrict the set of system calls applications can make, allowing cluster administrators greater control over the security of workloads ru
```suggestion
  description   = "Enable `docker/default` seccomp profile in your pod definitions."
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/section_5.sp
> +  description   = "Administrators should use default policies to isolate traffic in your cluster network. Running different applications on the same Kubernetes cluster creates a risk of one compromis
```suggestion
  description   = "Use network policies to isolate traffic in your cluster network."
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/section_5.sp
> +  description   = "Mounting service account tokens inside pods can provide an avenue for privilege escalation attacks where an attacker is able to compromise a single pod in the cluster. Avoiding mou
```suggestion
  description   = "Service accounts tokens should not be mounted in pods except where the workload running in the pod explicitly needs to communicate with the API server"
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/section_5.sp
> +  description   = "The principle of least privilege recommends that users are provided only the access required for their role and nothing more. The use of wildcard rights grants is likely to provide
```suggestion
  description   = "Kubernetes Roles and ClusterRoles provide access to resources based on sets of objects and actions that can be taken on those objects. It is possible to set either of these to be the wildcard "*" which matches all items. Use of wildcards is not optimal from a security perspective as it may allow for inadvertent access to be granted when new resources are added to the Kubernetes API either as CRDs or in later versions of the product."
```

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/section_5.sp
> +  title = "5.3 Network Policies and CNI"
Do we leave a benchmark without a description if not present in CIS document? Can you confirm?

2023-05-17 13:47 UTC, madhushreeray30 commented on cis_v170/cis.sp
We do add seperate .md files for sub-benchmarks. Can you please add them, thanks!!

2023-05-17 18:44 UTC, misraved commented on README.md
> +* [CIS v1.7.0](https://hub.steampipe.io/mods/turbot/kubernetes_compliance/controls/benchmark.cis_v170) 🚀 New!
```suggestion
* [CIS Kubernetes v1.7.0](https://hub.steampipe.io/mods/turbot/kubernetes_compliance/controls/benchmark.cis_v170) 🚀 New!
```

2023-05-18 06:50 UTC, misraved commented on query/role.sp
> +        when rule ->> 'verbs' like '%*%' then name || ' actions uses wildcard.'
```suggestion
        when rule ->> 'apiGroups' like '%*%' then name || ' api groups use wildcards.'
        when rule ->> 'resources' like '%*%' then name || ' resources use wildcards.'
        when rule ->> 'verbs' like '%*%' then name || ' actions use wildcards.'
```

2023-05-18 07:40 UTC, misraved approved these changes

2023-05-18 07:40 UTC, misraved approved these changes

2023-05-18 07:40 UTC, merged